background="background"
text="#D4BE98"
subtle="#4271AE"
warning-text="#D7005F"
text-special-one="#969694"
text-special-two="#D7005F"
top-bar-background="background"
top-bar-text="#66ff99"
status-bar-background="#4271AE"
status-bar-text="#EEEEEE"
status-bar-view-background="background"
status-bar-view-text="#D7005F"
command-text="#4271AE"
list-selected-background="#66ff99"
list-selected-text="#000000"
list-selected-inactive-background=""
list-selected-inactive-text=""
controls-text="#5c3d3d"
controls-highlight=""
autocomplete-background=""
autocomplete-text=""
autocomplete-selected-background=""
autocomplete-selected-text=""
button-color-one="#82FF79"
button-color-two=""
timeline-name-background=""
timeline-name-text="#99cc00"